app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'auth'],function(){

	Route::group(['middleware'=>'activo'],function(){

		Route::get('/inicio', ['as' =>'home.index' , 'uses' => 'HomeController@index']);

		Route::get('/', function () {
			return redirect()->route('home.index');
		});

		Route::get('perfil/index',['uses' => 'PerfilesController@index','as' => 'perfil.index']);
		Route::put('perfil/update/{user}',['uses' => 'PerfilesController@update','as' => 'perfil.update']);
		
		Route::get('solicitudes/{solicitud}/aprobar', ['as' =>'solicitudes.aprobar' , 'uses' => 'SolicitudesLivianosController@aprobar']);
		Route::put('solicitudes/{solicitud}/rechazar', ['as' =>'solicitudes.rechazar' , 'uses' => 'SolicitudesLivianosController@rechazar']);
		Route::get('solicitudes/{estado}/getCiudad', ['as' =>'solicitudes.getCiudad' , 'uses' => 'SolicitudesLivianosController@getCiudad']);
		Route::get('solicitudes/listar/{option?}', ['as' =>'solicitudes.listar' , 'uses' => 'SolicitudesLivianosController@listar']);
		Route::get('solicitudes/supervisor', ['as' =>'solicitudes.supervisor' , 'uses' => 'SolicitudesLivianosController@supervisor']);
		Route::resource('solicitudes', 'SolicitudesLivianosController');

		Route::get('sitios/padres', 'SitiosController@padres');
		Route::get('sitios/listar', ['as' =>'sitios.listar' , 'uses' => 'SitiosController@listar']);
		Route::resource('sitios', 'SitiosController');

		Route::group(['middleware'=>'user_admin'],function(){
			Route::get('usuarios/listar', ['as' =>'usuarios.listar' , 'uses' => 'UsuariosController@listar']);
			Route::get('usuarios', ['as' =>'usuarios.index' , 'uses' => 'UsuariosController@index']);
			Route::post('usuarios', ['as' =>'usuarios.store' , 'uses' => 'UsuariosController@store']);
			Route::delete('usuarios/{usuario}', ['as' =>'usuarios.destroy' , 'uses' => 'UsuariosController@destroy']);
			Route::put('usuarios/{usuario}', ['as' =>'usuarios.update' , 'uses' => 'UsuariosController@update']);	
			Route::get('usuarios/{usuario}', ['as' =>'usuarios.show' , 'uses' => 'UsuariosController@show']);
			Route::get('departamentos/opciones', 'DepartamentosController@opciones');
			Route::get('departamentos/listar', ['as' =>'departamentos.listar' , 'uses' => 'DepartamentosController@listar']);
			Route::resource('departamentos', 'DepartamentosController');
			Route::get('roles/listar', ['as' =>'roles.listar' , 'uses' => 'RolesController@listar']);
			Route::resource('roles', 'RolesController');
			Route::get('/mantenimiento', function () {
				$li='mantenimiento';
				return view('dashboard.mantenimiento.index')->with('li',$li);
				});		
		});

		Route::group(['middleware'=>'app_admin'],function(){
			Route::get('empleados/listar', ['as' =>'empleados.listar' , 'uses' => 'EmpleadosController@listar']);
			Route::resource('empleados', 'EmpleadosController');

			Route::get('proveedores/listar', ['as' =>'proveedores.listar' , 'uses' => 'ProveedoresController@listar']);
			Route::resource('proveedores', 'ProveedoresController');

			Route::get('proveedores/listar', ['as' =>'proveedores.listar' , 'uses' => 'ProveedoresController@listar']);
			Route::resource('proveedores', 'ProveedoresController');

			Route::get('viajes/{viaje}/por_unidad', ['as' =>'viajes.por_unidad' , 'uses' => 'ViajesController@por_unidad']);
			Route::get('viajes/cerrados', ['as' =>'viajes.cerrados' , 'uses' => 'ViajesController@cerrados']);
			Route::put('viajes/completar/{viaje}', ['as' =>'viajes.completar' , 'uses' => 'ViajesController@completar']);
			Route::get('viajes/{viaje}/cerrar', ['as' =>'viajes.cerrar' , 'uses' => 'ViajesController@cerrar']);
			Route::put('viajes/asignar', ['as' =>'viajes.asignar' , 'uses' => 'ViajesController@asignar']);
			Route::get('viajes/opciones', 'ViajesController@opciones');
			Route::post('viajes/nuevo', ['as' =>'viajes.nuevo' , 'uses' => 'ViajesController@nuevo']);
			Route::put('viajes/solicitudes_rechazar', ['as' =>'viajes.solicitudes_rechazar' , 'uses' => 'ViajesController@solicitudes_rechazar']);
			Route::get('viajes/solicitudes_listar/{option?}', ['as' =>'viajes.solicitudes_listar' , 'uses' => 'ViajesController@solicitudes_listar']);
			Route::get('viajes/listar/{option?}', ['as' =>'viajes.listar' , 'uses' => 'ViajesController@listar']);
			Route::resource('viajes', 'ViajesController');		

			Route::get('movimientos/listar', ['as' =>'movimientos.listar' , 'uses' => 'MovimientosController@listar']);
			Route::get('movimientos/{articulo}/movimientos', ['as' =>'movimientos.movimientos' , 'uses' => 'MovimientosController@movimientos']);
			Route::resource('movimientos', 'MovimientosController');

			Route::get('articulos/listar', ['as' =>'articulos.listar' , 'uses' => 'ArticulosController@listar']);
			Route::resource('articulos', 'ArticulosController');

			Route::get('activos/{activo}/pdf', ['as' =>'activos.pdf' , 'uses' => 'ActivosController@pdf']);
			Route::get('activos/listar', ['as' =>'activos.listar' , 'uses' => 'ActivosController@listar']);
			Route::resource('activos', 'ActivosController');

			Route::get('reportes/listar', ['as' =>'reportes.listar' , 'uses' => 'ReporteController@listar']);
			Route::resource('reportes', 'ReporteController');

			Route::get('ordenes/{orden}/pdf', ['as' =>'ordenes.pdf' , 'uses' => 'OrdenController@pdf']);
			Route::put('ordenes/completar/{orden}', ['as' =>'ordenes.completar' , 'uses' => 'OrdenController@completar']);
			Route::get('ordenes/{orden}/cambiar/{estado}', ['as' =>'ordenes.cambiar' , 'uses' => 'OrdenController@cambiar']);
			Route::delete('ordenes/borrar_movimiento/{movimiento}', ['as' =>'ordenes.borrar_movimiento' , 'uses' => 'OrdenController@borrar_movimiento']);
			Route::get('ordenes/getArticulos', ['as' =>'ordenes.getArticulos' , 'uses' => 'OrdenController@getArticulos']);
			Route::post('ordenes/agregar_tarea', ['as' =>'ordenes.agregar_tarea' , 'uses' => 'OrdenController@agregar_tarea']);
			Route::delete('ordenes/{orden}/borrar_tarea/{tarea}', ['as' =>'ordenes.borrar_tarea' , 'uses' => 'OrdenController@borrar_tarea']);
			Route::get('ordenes/{activo}/getTareas', ['as' =>'ordenes.getTareas' , 'uses' => 'OrdenController@getTareas']);
			Route::get('ordenes/listar', ['as' =>'ordenes.listar' , 'uses' => 'OrdenController@listar']);
			Route::resource('ordenes', 'OrdenController');

			//RUTAS DE LAS TAREAS CON ACTIVO ENLAZADO DE UNA VEZ
			Route::post('activo-tarea', ['as' =>'activo-tarea.store' , 'uses' => 'ActivoTareaController@store']);
			Route::get('activo-tarea/{pivot}', ['as' =>'activo-tarea.show' , 'uses' => 'ActivoTareaController@show']);
			Route::put('activo-tarea/{pivot}', ['as' =>'activo-tarea.update' , 'uses' => 'ActivoTareaController@update']);
			Route::delete('activo-tarea/{activo}/{tarea}', ['as' =>'activo-tarea.destroy' , 'uses' => 'ActivoTareaController@destroy']);
			Route::get('activo-tarea/{activo}/listar', ['as' =>'activo-tarea.listar' , 'uses' => 'ActivoTareaController@listar']);

			//RUTAS DE LOS REPORTES CON ACTIVO ENLAZADO DE UNA VEZ
			Route::get('activo-reporte/{reporte}/orden', ['as' =>'activo-reporte.orden' , 'uses' => 'ActivoReporteController@orden']);
			Route::get('activo-reporte/{reporte}/pdf', ['as' =>'activo-reporte.pdf' , 'uses' => 'ActivoReporteController@pdf']);
			Route::get('activo-reporte/{reporte}', ['as' =>'activo-reporte.show' , 'uses' => 'ActivoReporteController@show']);
			Route::get('activo-reporte/{activo}/listar', ['as' =>'activo-reporte.listar' , 'uses' => 'ActivoReporteController@listar']);

			//RUTAS DE LOS ARCHIVOS CON ACTIVO ENLAZADO DE UNA VEZ
			Route::get('activo-archivo/{activo}/nuevo', ['as' =>'activo-archivo.crear' , 'uses' => 'ActivoArchivoController@crear']);
			Route::get('activo-archivo/{activo}/listar', ['as' =>'activo-archivo.listar' , 'uses' => 'ActivoArchivoController@listar']);
			Route::resource('activo-archivo', 'ActivoArchivoController');

			//RUTAS DE LAS ORDENES CON ACTIVO Y/O ENLAZADO DE UNA VEZ
			Route::get('activo-orden/{activo}/nuevo', ['as' =>'activo-orden.nuevo' , 'uses' => 'ActivoOrdenController@nuevo']);
			Route::get('activo-orden/{activo}/listar', ['as' =>'activo-orden.listar' , 'uses' => 'ActivoOrdenController@listar']);			
		});
	});
});


Route::auth();

app/Reporte.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reporte extends Model
{
    protected $table = 'reportes';
    protected $fillable = [
    						'activo_id',
                            'creador_id',
                            'modificador_id',
                            'fecha',
                            'lugar',
                            'informador',
                            'ci_informador',
                            'cargo_informador',
							'observacion',			
							'estado',
                            'prioridad',
                            'created_at'
                        ];
							
	public function activo()
	    {
	    	return $this->belongsTo('App\Activo','activo_id');
	    }
    public function creador()
        {
            return $this->belongsTo('App\User','creador_id');
        }
    public function modificador()
        {
            return $this->belongsTo('App\User','modificador_id');
        }
	public function orden()
    	{
        	return $this->hasOne('App\Orden', 'reporte_id');
    	}
    public function fallas()
    {
        return $this->hasMany('App\Falla', 'reporte_id');
    }
    public function archivos()
    {
        return $this->hasMany('App\Archivo', 'reporte_id');
    }
}

resources/views/dashboard/reportes/form.blade.php
@extends('templates.master')

@section('title', 'Reportes')

@section('css')
<!-- fileinput --> 
<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/bootstrap-fileinput-master/css/fileinput.css') }}">

<!-- Select2 -->  
<link rel="stylesheet" href="{{asset('public/plugins/select2/dist/css/select2.min.css') }}">


@endsection

@section('contenido')
<div class="row">
  <div class="col-md-offset-2 col-md-8">
      <div class=" box box-success ">
    <div class="box-header with-border">
        <h3 class="box-title">Formulario para Reportes de fallas</h3>
    </div>
    <div class="box-body" >

      @if(isset($reporte))
      {!! Form::open(['method' => 'PUT','route' => ['reportes.update', $reporte->id] ,'class' => 'form-horizontal', 'files' => true,'enctype'=>"multipart/form-data"]) !!}
      {!! Form::hidden('id', $reporte->id) !!}  
      @else
      {!! Form::open(['method' => 'POST', 'route' => 'reportes.store', 'class' => 'form-horizontal', 'files' => true,'enctype'=>"multipart/form-data"]) !!} 
      @endif

        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">

        <div class=" form-group {{ $errors->has('activo_id') ? ' has-error' : '' }}">
            {!! Form::label('activo_id', 'Unidad / Equipo:', ['class' => 'col-sm-4 control-label']) !!}
            <div class="col-sm-7">
            {!! Form::select('activo_id', $activos , (isset($reporte)?$reporte->activo_id:null), ['id' => 'activo_id', 'class' => 'form-control select2','required' => 'required','placeholder'=> 'Seleccione']) !!}
            <small class="text-danger">{{ $errors->first('activo_id') }}</small>
            </div>
        </div>
        <div class="  form-group {{ $errors->has('fecha') ? ' has-error' : '' }}">
            {!! Form::label('fecha', 'Fecha:', ['class' => 'col-sm-4 control-label']) !!}
            <div class="col-sm-7">
              <div class="input-group date">
                <div class="input-group-addon">
                  <i class="fa fa-calendar"></i>
                </div>
                {!! Form::date('fecha', (isset($reporte)?$reporte->fecha:null), ['class' => 'form-control', 'required' => 'required']) !!}
              </div>          
              <small class="text-danger">{{ $errors->first('fecha') }}</small>
            </div>
        </div>
        <div class="form-group{{ $errors->has('prioridad') ? ' has-error' : '' }}">
            {!! Form::label('prioridad', 'Prioridad:', ['class' => 'col-sm-4 control-label']) !!}
            <div class="col-sm-7">
              {!! Form::select('prioridad', ['Baja'=>'Baja','Media'=>'Media', 'Alta'=>'Alta'], (isset($reporte)?$reporte->prioridad:null), ['id' => 'prioridad', 'class' => 'form-control', 'required' => 'required', 'placeholder'=>'Seleccione']) !!}
              <small class="text-danger">{{ $errors->first('prioridad') }}</small>
            </div>
        </div>
        <div class="form-group{{ $errors->has('lugar') ? ' has-error' : '' }}">
            {!! Form::label('lugar', 'Lugar/Ubicación:', ['class' => 'col-sm-4 control-label']) !!}
            <div class="col-sm-7">
              {!! Form::text('lugar', (isset($reporte)?$reporte->lugar:null), ['class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('lugar') }}</small>
            </div>
        </div>
        <div class=" form-group{{ $errors->has('informador') ? ' has-error' : '' }}">
          {!! Form::label('informador', 'Reportado por:', ['class' => 'col-sm-4 control-label']) !!}
          <div class="col-sm-7">
            {!! Form::text('informador', (isset($reporte)?$reporte->informador:null), ['class' => 'form-control', 'required' => 'required', 'placeholder'=>'Nombre Completo']) !!}
            <small class="text-danger">{{ $errors->first('informador') }}</small> 
          </div>
        </div>
        <div class="form-group{{ $errors->has('ci_informador') ? ' has-error' : '' }}">
          {!! Form::label('ci_informador', 'C.I.:', ['class' => 'col-sm-4 control-label']) !!}
          <div class="col-sm-7">
            {!! Form::text('ci_informador', (isset($reporte)?$reporte->ci_informador:null), ['class' => 'form-control', 'placeholder'=>'23.533.432','required']) !!}
            <small class="text-danger">{{ $errors->first('ci_informador') }}</small>    
          </div>                
        </div>
        <div class="form-group{{ $errors->has('cargo_informador') ? ' has-error' : '' }}">
            {!! Form::label('cargo_informador', 'Cargo:',['class' => 'col-sm-4 control-label']) !!}
            <div class="col-sm-7">
              {!! Form::text('cargo_informador', (isset($reporte)?$reporte->cargo_informador:null), ['class' => 'form-control', 'required' => 'required', 'placeholder'=>'Cargo desempeñado']) !!}
              <small class="text-danger">{{ $errors->first('cargo_informador') }}</small>  
            </div>           
        </div>
        <div class="pull-right">
          <button type="button" class="btn btn-info btn-xs" data-toggle="tooltip" data-placement="top" title="Agregar" id="nuevo" OnClick="agregar()">Agregar Falla</button>

          <button type="button" class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" title="Eliminar" id="borrar" OnClick="coño()">Eliminar Falla</button>
        </div><br /> <br />
        @if(isset($reporte))
          @for($i = 0; $i < $reporte->fallas->count(); $i++)
            <div id="cel" class="clonedcel">
              <div class=" form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                {!! Form::label('nombre[]', 'Falla y Tipo: ',['class' => 'col-sm-4 control-label']) !!}
                <div class="col-sm-4">
                  {!! Form::text('nombre[]', $reporte->fallas[$i]->nombre, ['id' => 'nombre[]', 'class' => 'form-control','maxlength'=>200,'minlength'=>5 ]) !!}
                  <small class="text-danger">{{ $errors->first('nombre') }}</small>                  
                </div>
                <div class="col-sm-3">
                  {!! Form::select('tipo[]', ['Combustible'=>'Combustible','Electrica'=>'Electrica','Hidraulica'=>'Hidraulica','Mecanica'=>'Mecanica', 'Neumatica'=>'Neumatica' ],  $reporte->fallas[$i]->tipo, ['id' => 'tipo[]', 'class' => 'form-control','placeholder'=>'Seleccione']) !!}
                </div>
              </div>
            </div>         
          @endfor 
          <div id="input1" class="clonedInput">
            <div class=" form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
              {!! Form::label('nombre[]', 'Falla y Tipo: ',['class' => 'col-sm-4 control-label']) !!}
              <div class="col-sm-4">
                {!! Form::text('nombre[]', null, ['id' => 'nombre[]', 'class' => 'form-control','maxlength'=>200,'minlength'=>5 ]) !!}
                <small class="text-danger">{{ $errors->first('nombre') }}</small>                  
              </div>
              <div class="col-sm-3">
                {!! Form::select('tipo[]', ['Combustible'=>'Combustible','Electrica'=>'Electrica','Hidraulica'=>'Hidraulica','Mecanica'=>'Mecanica', 'Neumatica'=>'Neumatica' ], null, ['id' => 'tipo[]', 'class' => 'form-control', 'placeholder'=>'Seleccione']) !!}
              </div>
            </div>
          </div>
        @else
        <div id="input1" class="clonedInput">
          <div class=" form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
            {!! Form::label('nombre[]', 'Falla y Tipo: ',['class' => 'col-sm-4 control-label']) !!}
            <div class="col-sm-4">
              {!! Form::text('nombre[]', null, ['id' => 'nombre[]', 'class' => 'form-control', 'maxlength'=>200,'minlength'=>5, 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('nombre') }}</small>                  
            </div>
            <div class="col-sm-3">
              {!! Form::select('tipo[]', ['Combustible'=>'Combustible','Electrica'=>'Electrica','Hidraulica'=>'Hidraulica','Mecanica'=>'Mecanica', 'Neumatica'=>'Neumatica' ], null, ['id' => 'tipo[]', 'class' => 'form-control', 'placeholder'=>'Seleccione', 'required' => 'required']) !!}
            </div>
          </div>
        </div>
        @endif 
        <div class=" form-group {{ $errors->has('observacion') ? ' has-error' : '' }}">
            {!! Form::label('observacion', 'Observaciones:',['class' => 'col-sm-4 control-label']) !!}
            <div class="col-sm-7">
              {!! Form::textarea('observacion', (isset($reporte)?$reporte->observacion:null), ['class' => 'form-control', 'required' => 'required','rows'=>3]) !!}
              <small class="text-danger">{{ $errors->first('observacion') }}</small>
            </div>
        </div> 
        @if(isset($reporte))
          @if($reporte->archivos->count() >0 )
          <div class="row">
            <div class="col-sm-4">
              <b class="pull-right">Archivos actuales:</b>
            </div>
            <div class="col-sm-7">
              <table class="table table-responsive " cellspacing="0">
                <thead  style="color:gray; ">
                  <tr>
                    <th style="text-align: center; width:10%">Eliminar</th>
                    <th style="text-align: center; width:30%">Nombre del archivo</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($reporte->archivos as $archivo)
                  <tr >
                    <td style="text-align: center;"><input type="checkbox" value="{{ $archivo->id}}" name="eliminar[]"></td>
                    <td >
                      <a href="{{asset('public/image/archivos/'.$archivo->nombre_interno) }} " target="_blank">
                        {{ $archivo->nombre_externo}}
                      </a>
                    </td>
                  </tr>
                  @endforeach  
                </tbody> 
              </table>            
            </div>
          </div>
          @endif 
        @endif
        <div class=" form-group {{ $errors->has('archivo')?' has-error':'' }}">
          {!! Form::label('archivo', 'Archivo(s):',['class' => 'col-sm-4 control-label']) !!}
          <div class="col-sm-7">
            <input type="file" name="archivo[]" id='archivo' multiple="">
            <p class="help-block">Si es mas de un archivo, debe seleccionarlos al mismo tiempo (deben estar en la misma ubicación). Recuerde que si quiere visualizar las imagenes en los reportes impresos, estas deben estar en formato jpg o png.</p>
            @if($errors->has('archivo'))
            <span class="text-danger">
              <strong>{{ $errors->first('archivo')}}</strong>
            </span>
            @endif
          </div>
        </div>          
    </div>  
    <div class="box-footer with-border">
        <div class="col-md-4 col-md-offset-5">
          <a href="{{ URL::previous() }}" class="btn btn-info ">Cancelar</a>
          {!! Form::submit('Guardar', ['class' => 'btn btn-success']) !!}     
        </div>
    </div>       
      {!! Form::close() !!}
  </div> 
  </div>
  
</div>
  
  
@endsection

@section('js')

<!-- fileinput -->
<script src="{{asset('public/plugins/bootstrap-fileinput-master/js/fileinput.js')}}"></script>
<script src="{{asset('public/plugins/bootstrap-fileinput-master/js/locales/es.js')}}"></script>

<!-- Select2 -->  
<script src="{{asset('public/plugins/select2/dist/js/select2.full.min.js')}}"></script>
<script src="{{asset('public/plugins/select2/dist/js/i18n/es.js') }}"></script>

<script>


  $(function() {
    //<!-- fileinput -->
    $('#archivo').fileinput({
    showUpload: false,
    language: 'es',
    browseClass: "btn btn-info",
    maxFileSize: 500,
    maxFileCount: 5,
    overwriteInitial: false,
    })
    //<!-- fileinput -->
  });  

  $("#activo_id").select2({
  placeholder: "Seleccione",
  width:'100%',
  language: "es",
  })

</script>



<script type="text/javascript">
        
function agregar(){

    var num     = $('.clonedInput').length;
    var newNum  = new Number(num + 1);

    var newElem = $('#input' + num).clone().attr('id', 'input' + newNum);

    $('#input' + num).after(newElem);
    $('#borrar').attr('disabled',false);

    if (newNum == 5)
        $('#nuevo').attr('disabled','disabled');
};


function coño(){
    var num = $('.clonedInput').length;

    $('#input' + num).remove();
    $('#nuevo').attr('disabled',false);

    if (num-1 == 1)
        $('#borrar').attr('disabled','disabled');
};

$('#borrar').attr('disabled','');
   
</script>

@endsection

resources/views/dashboard/reportes/index.blade.php
@extends('templates.master')

@section('title', 'Reportes')

@section('css')

<!-- DataTables -->  
<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/datatables/dataTables.bootstrap.css')}}">

<style type="text/css">
  .badge-warning {
    background-color: #FF9800;
  }
  .badge-boton {
    background-color: #FFCA28;
  }

</style>
@endsection

@section('contenido')
{!! Form::hidden('token', csrf_token(), ['id'=>'token']) !!}
<div class="row" >
  <div class="col-md-12">
    <div class="box box-success">
      <div class="box-body">
        <a class="btn btn-default" href="{{route('reportes.create')}}"><span class="text-success"><i class="fa fa-plus"></i></span> Agregar Reporte</a>
        <a href='javascript:void(0)' class="btn btn-default pull-right"  id="actualizar-reportes"><i class="fa fa-repeat"></i> Actualizar</a>
        <br>
        <hr>
        <table class="table table-bordered table-hover table-striped" id="tabla-reportes" >
          <thead>
            <tr>
              <th style="text-align: center;">ID</th>
              <th style="text-align: center;">Unidad/Equipo</th>
              <th style="text-align: center;">Reportado por</th>                  
              <th style="text-align: center;">Fecha</th>
              <th style="text-align: center;">Prioridad</th>                     
              <th style="text-align: center;">Orden de trabajo</th>
              <th style="text-align: center;"></th>

            </tr>
          </thead>
        </table>
      </div><!-- /.box-body -->
  </div>
</div>

@include('dashboard.activos.reportes.archivos')

@endsection

@section('js')

<!-- DataTables -->
<script src="{{asset('public/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/dataTables.bootstrap.min.js')}}"></script>

<script src="{{asset('public/js/reporte.js')}}"></script>

<script type="text/javascript">
  $.fn.dataTable.ext.errMode = 'throw';
</script>

@endsection