app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'auth'],function(){

	Route::group(['middleware'=>'activo'],function(){

		Route::get('/inicio', ['as' =>'home.index' , 'uses' => 'HomeController@index']);

		Route::get('/', function () {
			return redirect()->route('home.index');
		});

		Route::get('perfil/index',['uses' => 'PerfilesController@index','as' => 'perfil.index']);
		Route::put('perfil/update/{user}',['uses' => 'PerfilesController@update','as' => 'perfil.update']);
		
		Route::get('solicitudes/{solicitud}/aprobar', ['as' =>'solicitudes.aprobar' , 'uses' => 'SolicitudesLivianosController@aprobar']);
		Route::put('solicitudes/{solicitud}/rechazar', ['as' =>'solicitudes.rechazar' , 'uses' => 'SolicitudesLivianosController@rechazar']);
		Route::get('solicitudes/{estado}/getCiudad', ['as' =>'solicitudes.getCiudad' , 'uses' => 'SolicitudesLivianosController@getCiudad']);
		Route::get('solicitudes/listar/{option?}', ['as' =>'solicitudes.listar' , 'uses' => 'SolicitudesLivianosController@listar']);
		Route::get('solicitudes/supervisor', ['as' =>'solicitudes.supervisor' , 'uses' => 'SolicitudesLivianosController@supervisor']);
		Route::resource('solicitudes', 'SolicitudesLivianosController');

		Route::get('sitios/padres', 'SitiosController@padres');
		Route::get('sitios/listar', ['as' =>'sitios.listar' , 'uses' => 'SitiosController@listar']);
		Route::resource('sitios', 'SitiosController');

		Route::group(['middleware'=>'user_admin'],function(){
			Route::get('usuarios/listar', ['as' =>'usuarios.listar' , 'uses' => 'UsuariosController@listar']);
			Route::get('usuarios', ['as' =>'usuarios.index' , 'uses' => 'UsuariosController@index']);
			Route::post('usuarios', ['as' =>'usuarios.store' , 'uses' => 'UsuariosController@store']);
			Route::delete('usuarios/{usuario}', ['as' =>'usuarios.destroy' , 'uses' => 'UsuariosController@destroy']);
			Route::put('usuarios/{usuario}', ['as' =>'usuarios.update' , 'uses' => 'UsuariosController@update']);	
			Route::get('usuarios/{usuario}', ['as' =>'usuarios.show' , 'uses' => 'UsuariosController@show']);
			Route::get('departamentos/opciones', 'DepartamentosController@opciones');
			Route::get('departamentos/listar', ['as' =>'departamentos.listar' , 'uses' => 'DepartamentosController@listar']);
			Route::resource('departamentos', 'DepartamentosController');
			Route::get('roles/listar', ['as' =>'roles.listar' , 'uses' => 'RolesController@listar']);
			Route::resource('roles', 'RolesController');
			Route::get('/mantenimiento', function () {
				$li='mantenimiento';
				return view('dashboard.mantenimiento.index')->with('li',$li);
				});		
		});

		Route::group(['middleware'=>'app_admin'],function(){
			Route::get('empleados/listar', ['as' =>'empleados.listar' , 'uses' => 'EmpleadosController@listar']);
			Route::resource('empleados', 'EmpleadosController');

			Route::get('proveedores/listar', ['as' =>'proveedores.listar' , 'uses' => 'ProveedoresController@listar']);
			Route::resource('proveedores', 'ProveedoresController');

			Route::get('proveedores/listar', ['as' =>'proveedores.listar' , 'uses' => 'ProveedoresController@listar']);
			Route::resource('proveedores', 'ProveedoresController');

			Route::get('viajes/{viaje}/por_unidad', ['as' =>'viajes.por_unidad' , 'uses' => 'ViajesController@por_unidad']);
			Route::get('viajes/cerrados', ['as' =>'viajes.cerrados' , 'uses' => 'ViajesController@cerrados']);
			Route::put('viajes/completar/{viaje}', ['as' =>'viajes.completar' , 'uses' => 'ViajesController@completar']);
			Route::get('viajes/{viaje}/cerrar', ['as' =>'viajes.cerrar' , 'uses' => 'ViajesController@cerrar']);
			Route::put('viajes/asignar', ['as' =>'viajes.asignar' , 'uses' => 'ViajesController@asignar']);
			Route::get('viajes/opciones', 'ViajesController@opciones');
			Route::post('viajes/nuevo', ['as' =>'viajes.nuevo' , 'uses' => 'ViajesController@nuevo']);
			Route::put('viajes/solicitudes_rechazar', ['as' =>'viajes.solicitudes_rechazar' , 'uses' => 'ViajesController@solicitudes_rechazar']);
			Route::get('viajes/solicitudes_listar/{option?}', ['as' =>'viajes.solicitudes_listar' , 'uses' => 'ViajesController@solicitudes_listar']);
			Route::get('viajes/listar/{option?}', ['as' =>'viajes.listar' , 'uses' => 'ViajesController@listar']);
			Route::resource('viajes', 'ViajesController');		

			Route::get('movimientos/listar', ['as' =>'movimientos.listar' , 'uses' => 'MovimientosController@listar']);
			Route::get('movimientos/{articulo}/movimientos', ['as' =>'movimientos.movimientos' , 'uses' => 'MovimientosController@movimientos']);
			Route::resource('movimientos', 'MovimientosController');

			Route::get('articulos/listar', ['as' =>'articulos.listar' , 'uses' => 'ArticulosController@listar']);
			Route::resource('articulos', 'ArticulosController');

			Route::get('activos/{activo}/pdf', ['as' =>'activos.pdf' , 'uses' => 'ActivosController@pdf']);
			Route::get('activos/listar', ['as' =>'activos.listar' , 'uses' => 'ActivosController@listar']);
			Route::resource('activos', 'ActivosController');

			Route::get('reportes/listar', ['as' =>'reportes.listar' , 'uses' => 'ReporteController@listar']);
			Route::resource('reportes', 'ReporteController');

			Route::get('ordenes/{orden}/pdf', ['as' =>'ordenes.pdf' , 'uses' => 'OrdenController@pdf']);
			Route::put('ordenes/completar/{orden}', ['as' =>'ordenes.completar' , 'uses' => 'OrdenController@completar']);
			Route::get('ordenes/{orden}/cambiar/{estado}', ['as' =>'ordenes.cambiar' , 'uses' => 'OrdenController@cambiar']);
			Route::delete('ordenes/borrar_movimiento/{movimiento}', ['as' =>'ordenes.borrar_movimiento' , 'uses' => 'OrdenController@borrar_movimiento']);
			Route::get('ordenes/getArticulos', ['as' =>'ordenes.getArticulos' , 'uses' => 'OrdenController@getArticulos']);
			Route::post('ordenes/agregar_tarea', ['as' =>'ordenes.agregar_tarea' , 'uses' => 'OrdenController@agregar_tarea']);
			Route::delete('ordenes/{orden}/borrar_tarea/{tarea}', ['as' =>'ordenes.borrar_tarea' , 'uses' => 'OrdenController@borrar_tarea']);
			Route::get('ordenes/{activo}/getTareas', ['as' =>'ordenes.getTareas' , 'uses' => 'OrdenController@getTareas']);
			Route::get('ordenes/listar', ['as' =>'ordenes.listar' , 'uses' => 'OrdenController@listar']);
			Route::resource('ordenes', 'OrdenController');

			//RUTAS DE LAS TAREAS CON ACTIVO ENLAZADO DE UNA VEZ
			Route::post('activo-tarea', ['as' =>'activo-tarea.store' , 'uses' => 'ActivoTareaController@store']);
			Route::get('activo-tarea/{pivot}', ['as' =>'activo-tarea.show' , 'uses' => 'ActivoTareaController@show']);
			Route::put('activo-tarea/{pivot}', ['as' =>'activo-tarea.update' , 'uses' => 'ActivoTareaController@update']);
			Route::delete('activo-tarea/{activo}/{tarea}', ['as' =>'activo-tarea.destroy' , 'uses' => 'ActivoTareaController@destroy']);
			Route::get('activo-tarea/{activo}/listar', ['as' =>'activo-tarea.listar' , 'uses' => 'ActivoTareaController@listar']);

			//RUTAS DE LOS REPORTES CON ACTIVO ENLAZADO DE UNA VEZ
			Route::get('activo-reporte/{reporte}/orden', ['as' =>'activo-reporte.orden' , 'uses' => 'ActivoReporteController@orden']);
			Route::get('activo-reporte/{reporte}/pdf', ['as' =>'activo-reporte.pdf' , 'uses' => 'ActivoReporteController@pdf']);
			Route::get('activo-reporte/{reporte}', ['as' =>'activo-reporte.show' , 'uses' => 'ActivoReporteController@show']);
			Route::get('activo-reporte/{activo}/listar', ['as' =>'activo-reporte.listar' , 'uses' => 'ActivoReporteController@listar']);

			//RUTAS DE LOS ARCHIVOS CON ACTIVO ENLAZADO DE UNA VEZ
			Route::get('activo-archivo/{activo}/nuevo', ['as' =>'activo-archivo.crear' , 'uses' => 'ActivoArchivoController@crear']);
			Route::get('activo-archivo/{activo}/listar', ['as' =>'activo-archivo.listar' , 'uses' => 'ActivoArchivoController@listar']);
			Route::resource('activo-archivo', 'ActivoArchivoController');

			//RUTAS DE LAS ORDENES CON ACTIVO Y/O ENLAZADO DE UNA VEZ
			Route::get('activo-orden/{activo}/nuevo', ['as' =>'activo-orden.nuevo' , 'uses' => 'ActivoOrdenController@nuevo']);
			Route::get('activo-orden/{activo}/listar', ['as' =>'activo-orden.listar' , 'uses' => 'ActivoOrdenController@listar']);			
		});
	});
});


Route::auth();

resources/views/dashboard/ordenes/complete.blade.php
<!-- Modal -->
<div class="modal fade" id="modal-compleado" data-keyboard="false" data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content box">
      <div class="modal-header text-center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Completar Orden de trabajo</h4>
      </div>
      <div class="modal-body">
        {!! Form::open(['id'=>'form-estado']) !!}
        {!! Form::hidden('token', csrf_token(), ['id'=>'token']) !!}
        {!! Form::hidden('activo_id', $orden->activo->id, ['id'=>'activo_id']) !!}
        {!! Form::hidden('orden_id', $orden->id, ['id'=>'orden_id']) !!}

        <div class=" col-md-12 form-group" id="field-termina">
            {!! Form::label('termina', 'Fecha de Completación', ['class' => 'col-sm-5 control-label text-right']) !!}
            <div class="col-sm-6">
              {!! Form::date('termina', null, ['id'=>'termina','class' => 'form-control', 'required' => 'required']) !!}
              <small class="text-danger">{{ $errors->first('termina') }}</small>
            </div>
        </div>
        @if($orden->activo->medida != null)
          @if($orden->activo->medida->horas > 0 || $orden->activo->medida->horas != null)
          <div class=" col-md-12 form-group " id="field-horas">
              {!! Form::label('horas', 'Horas', ['class' => 'col-sm-5 control-label text-right']) !!}
              <div class="col-sm-6">
                {!! Form::number('horas', $orden->activo->medida->horas, ['id'=>'horas', 'class' => 'form-control', 'required' => 'required']) !!}
                <small class="text-danger">{{ $errors->first('horas') }}</small>
            </div>
          </div>
          @endif
          @if($orden->activo->medida->kilometros > 0 || $orden->activo->medida->kilometros != 0)
          <div class=" col-md-12 form-group" id="field-kilometros">
              {!! Form::label('kilometros', 'Kilometros', ['class' => 'col-sm-5 control-label text-right']) !!}
              <div class="col-sm-6">
                {!! Form::number('kilometros', $orden->activo->medida->kilometros, ['id'=>'kilometros', 'class' => 'form-control', 'required' => 'required']) !!}
                <small class="text-danger">{{ $errors->first('kilometros') }}</small>
            </div>
          </div>
          @endif
        @endif
        <br /><br /><br /><br /><br /><br /><br />     
      </div>
      <div class="modal-footer">
        <div class="pull-right">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
          <button type="button" id="guardar-completar" class="btn btn-success" data-loading-text="Guardando..." autocomplete="off">Guardar</button>
          {!! Form::close() !!}
        </div>      
      </div>
    </div>
  </div>
</div>

resources/views/dashboard/ordenes/index.blade.php
@extends('templates.master')

@section('title', 'Ordenes')

@section('css')

<!-- DataTables -->  
<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/datatables/dataTables.bootstrap.css')}}">

@endsection

@section('contenido')
{!! Form::hidden('token', csrf_token(), ['id'=>'token']) !!}
<div class="row" >
  <div class="col-md-12">
    <div class="box box-success">
      <div class="box-body">
        <a class="btn btn-default" href="{{route('ordenes.create')}}"><span class="text-success"><i class="fa fa-plus"></i></span> Crear Orden</a>
        <a href='javascript:void(0)' class="btn btn-default pull-right"  id="actualizar-ordenes"><i class="fa fa-repeat"></i> Actualizar</a>
        <br>
        <hr>
        <table class="table table-bordered table-hover table-striped" id="tabla-ordenes" >
          <thead>
            <tr>
              <th style="text-align: center;">Nro.</th>
              <th style="text-align: center;">Fecha de Inicio</th>
              <th style="text-align: center;">Fecha de Fin</th>
              <th style="text-align: center;">Responsable</th>
              <th style="text-align: center;">Unidad/Equipo</th>
              <th style="text-align: center;">Estado</th>
            </tr>
          </thead>
        </table>
      </div><!-- /.box-body -->
  </div>
</div>

@endsection

@section('js')

<!-- DataTables -->
<script src="{{asset('public/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/dataTables.bootstrap.min.js')}}"></script>

<script src="{{asset('public/js/orden.js')}}"></script>

<script type="text/javascript">
  $.fn.dataTable.ext.errMode = 'throw';
</script>

@endsection

resources/views/dashboard/ordenes/show.blade.php
@extends('templates.master')

@section('title', 'Ordenes')

@section('css')
<!-- Select2 -->  
<link rel="stylesheet" href="{{asset('public/plugins/select2/dist/css/select2.min.css') }}">

<meta name="csrf-token" content="{{ csrf_token() }}">

<style type="text/css">
.custom {
    width: 100px !important;
    height: 50px !important;
    margin-right: 5px !important;
}

</style>
@endsection


@section('contenido')
 
<div class="box box-success" >
  <div class="box-header"  id="botones"><br />
    <div class="row">
      <div class="col-md-3">
        <b style="font-size: 20px">Orden de Trabajo Nro. {{$orden->id}}</b>
      </div>
      <div class="col-md-3">
        <div class="btn-group">
          @if($orden->estado_orden != 'completada')
          <a class="btn btn-default" href="{{route('ordenes.edit', $orden->id)}}" title="Eliminar"><i class="fa fa-fw fa-pencil"></i></a>
          @endif
          <a href="{{route('ordenes.pdf', $orden->id)}}" class="btn btn-default" title="PDF" target="_blank"><i class="fa fa-file-pdf-o"></i></a>
          <a class="btn btn-default" OnClick="delete_Orden('{{$orden->id}}')" title="Eliminar" ><i class="fa fa-fw fa-trash"></i></a>
        </div>
      </div>
      <div class="col-md-6">
        <button type="button" @if($orden->estado_orden == 'abierta') class="btn btn-success custom " disabled="true" @else class="btn btn-default custom " @endif style="font-size: 12px" onclick="cambiarEstado('{{$orden->id}}','abierta')"><b>ABIERTA</b></button>
        <button type="button" @if($orden->estado_orden == 'en progreso') class="btn btn-warning custom " disabled="true" @else class="btn btn-default custom " @endif style="font-size: 12px" onclick="cambiarEstado('{{$orden->id}}',3)"><b>EN PROCESO</b></button>
        <button type="button" @if($orden->estado_orden == 'detenida') class="btn btn-danger custom " disabled="true" @else class="btn btn-default custom " @endif style="font-size: 12px" onclick="cambiarEstado('{{$orden->id}}','detenida')"><b>DETENIDA</b></button>
        <button type="button" @if($orden->estado_orden == 'completada') class="btn btn-info custom " disabled="true" @else class="btn btn-default custom " @endif style="font-size: 12px"  data-toggle="modal" data-target="#modal-compleado"><b>COMPLETADA</b></button>
      </div>
    </div>
  </div>
  <div class="box-body" >
    <div id="detalles" class="row">
      <div id="detalles_orden" class="col-md-5">
        <table class="table" style="border:hidden; ">
          <tr style="border:hidden;">
            <td style="color: #605F5F">Unidad/Equipo:</td><td>
              <a href="{{route('activos.show',$orden->activo->id)}}">
                {{$orden->activo->unidad}} {{$orden->activo->placa}} {{$orden->activo->marca}} {{$orden->activo->modelo}} { {{$orden->activo->nro_activo}} }
              </a>
            </td>
          </tr>          
          <tr style="border:hidden;">
            <td style="color: #605F5F">Responsable:</td><td>{{$orden->empleado->nombre}}</td>
          </tr>
          <tr style="border:hidden;">
            <td style="color: #605F5F">Prioridad:</td><td  style="color: @if($orden->Alta == 'Alta') red @else orange @endif">{{$orden->prioridad}}</td>
          </tr>
          <tr style="border:hidden;">
            <td style="color: #605F5F">Fecha de Inicio:</td><td>{{$orden->inicia}}</td>
          </tr>
          @if($orden->estado_orden == 'completada')
          <tr style="border:hidden;">
            <td style="color: #605F5F">Fecha de Fin:</td><td>{{$orden->termina}}</td>
          </tr>
          @endif
        </table>
      </div>
      @if($orden->reporte)
      <div id="detalles_reporte" class="col-md-7">
        <table class="table" style="border:hidden; ">
          <tr style="border:hidden;">
            <td style="color: #605F5F">Reporte de fallas:</td><td>
              <a href="{{route('activo-reporte.pdf',$orden->reporte->id)}}"  target="_blank">
                Nro .{{$orden->reporte->id}}
              </a>
            </td>
          </tr>          
          <tr style="border:hidden;">
            <td style="color: #605F5F">Reportado por:</td><td>{{$orden->reporte->informador}} {{$orden->reporte->cargo_informador}}</td>
          </tr>
          <tr style="border:hidden;">
            <td style="color: #605F5F">Tipo y descripcion de la fallas:</td>
              <td>
                @foreach ($orden->reporte->fallas as $falla)
                {{$falla->tipo}} - {{$falla->nombre}}.<br />
                @endforeach
              </td>
          </tr>
        </table>
      </div>
      @endif      
    </div>    
    <div >
      <table class="table table-hover" style="border:hidden; " id="tareas">
        <tr style="background-color: #E5E7E9">
          <td colspan="3" >TAREAS ASIGNADAS</td>
        </tr>
        @foreach ($orden->tareas as $tarea)
          <tr>
            <td class="text-center" width="10%"> 
              @if($tarea->pivot->status == 'completa')<i class="fa fa-fw fa-check text-success"></i> 
              @else <i class="fa fa-fw fa-clock-o text-warning"></i> 
              @endif
            </td>
            <td>{{$tarea->nombre}}</td>
            <td class="text-center" width="10%"> 
              @if($orden->estado_orden != 'completada')
                <?php if( count($orden->tareas) > 1) { ?>
                <button type="button" class="btn btn-danger btn-xs" onclick="delete_Tarea({{$orden->id}},{{$tarea->id}})">
                    <i class="fa fa-fw fa-trash"> </i>
                </button>   
                <?php }?>
              @endif
            </td>
          </tr>
        @endforeach
      </table>

      <div style="display:none" id="div1" >

        {!! Form::open(['id'=>'form-tarea']) !!}

          {!! Form::hidden('token', csrf_token(), ['id'=>'token']) !!}
          {!! Form::hidden('activo_id', $orden->activo->id, ['id'=>'activo_id']) !!}
          {!! Form::hidden('orden_id', $orden->id, ['id'=>'orden_id']) !!}
          
          
            <div class="col-md-6" id="select_tarea">
              {!! Form::select('tarea_id', [] , null, ['id' => 'tarea_id', 'class' => 'form-control select2', 'required' => 'required','placeholder'=> 'Seleccione']) !!}             
            </div> 
            
              <button type="button" id="guardar-tarea" class="btn btn-success " data-loading-text="Guardando..." autocomplete="off"><i class="fa fa-fw fa-save"></i></button>
              <button type="button" class="btn btn-default " onClick="cambiarDisplay('div1','div2')" ><i class="fa fa-fw fa-close"></i></button>
                  
        {!! Form::close() !!}
      <br />  
      </div>
      
      <div style="display;" id="div2" >
        @if($orden->estado_orden != 'completada')
        <button type="button" class="btn btn-default" data-toggle="modal" onClick="cambiarDisplay('div1','div2')">
          <span class="text-success"><i class="fa fa-plus"></i></span> Agregar Tarea
        </button>
        <br />
        <br />
        @endif
      </div>
      
    </div>

    
    <div >
      <table class="table table-hover " style="border:hidden; " id="articulos">
        <tr style="background-color: #E5E7E9">
          <td colspan="5" >ARTICULOS/INSUMOS ASIGNADOS</td>
        </tr>
        <tr style="background-color: #F5F8FA" class="text-center">
          <td style="width: 110px">Nro. de activo </td>
          <td >Articulo/Insumo</td>
          <td style="width: 110px">Cantidad</td>
          <td>Uso</td>
          <td style="width: 110px"></td>
        </tr>        
        @if(isset($orden->movimientos))
          @foreach ($orden->movimientos as $movimiento)
          <tr class="text-center">
            <td ><a href="{{route('articulos.edit',$movimiento->articulo->id)}}"> {{$movimiento->articulo->nro_activo}}</a></td>
            <td>{{$movimiento->articulo->nombre}}</td>
            <td>{{$movimiento->cantidad}}</td>
            <td class="text-justify">{{$movimiento->razon}}</td>
            <td>
              @if($orden->estado_orden != 'completada')
              <button type="button" class="btn btn-danger btn-xs" onclick="delete_Movimiento({{$movimiento->id}})">
                <i class="fa fa-fw fa-trash"> </i>
              </button>
              @endif
            </td>
          </tr>
          @endforeach
        @endif        
      </table>
      <div style="display:none" id="div3" >

        {!! Form::open(['id'=>'form-movimiento']) !!}

          {!! Form::hidden('token', csrf_token(), ['id'=>'token']) !!}
          {!! Form::hidden('tipo', 'SALIDA', ['id'=>'tipo']) !!}
          {!! Form::hidden('activo_id', $orden->activo->id, ['id'=>'activo_id']) !!}
          {!! Form::hidden('orden_id', $orden->id, ['id'=>'orden_id']) !!}

          <div class="row">
            <div class="col-md-4">
              {!! Form::select('articulo_id', [] , null, ['id' => 'articulo_id', 'class' => 'form-control select2', 'required' => 'required','placeholder'=> 'Seleccione']) !!}             
            </div>
            <div class="col-md-2" id="field-cantidad">
               {!! Form::number('cantidad', null, ['id' => 'cantidad','class' => 'form-control','min'=>0 ,'placeholder'=>'Cantidad']) !!}
            <span>
              <strong class="text-danger msj-error"></strong>
            </span>
            </div>
            <div class="col-md-4" id="field-razon">
              {!! Form::text('razon', null, ['id' => 'razon', 'class' => 'form-control', 'required' => 'required' ,'placeholder'=>'Razón de uso']) !!}
              <span>
                <strong class="text-danger msj-error"></strong>
              </span>
            </div>
            <div class="col-md-2">
              <button type="button" id="guardar-movimiento" class="btn btn-success" data-loading-text="..." autocomplete="off"><i class="fa fa-fw fa-save"></i></button>
              <button type="button" class="btn btn-default" onClick="cambiarDisplay('div3','div4')" ><i class="fa fa-fw fa-close"></i></button>
            </div>              
          </div>    
        {!! Form::close() !!}
      <br />  
      </div>
      
      <div style="display;" id="div4" >
        @if($orden->estado_orden != 'completada')
        <button type="button" class="btn btn-default" data-toggle="modal" onClick="cambiarDisplay('div3','div4')">
          <span class="text-success"><i class="fa fa-plus"></i></span> Agregar Articulo
        </button>
        <br />
        <br />
        @endif
      </div>            
    </div>
    <div >
      <table class="table table-hover " style="border:hidden; " id="notas">
        <tr style="background-color: #E5E7E9">
          <td >NOTAS</td>
        </tr>
        <tr >
          <td>{{$orden->notas}}</td>
        </tr>               
      </table>     
    </div>
  </div>

</div>

@include('dashboard.ordenes.complete')

@endsection

@section('js')

<!-- Select2 -->  
<script src="{{asset('public/plugins/select2/dist/js/select2.full.min.js')}}"></script>
<script src="{{asset('public/plugins/select2/dist/js/i18n/es.js') }}"></script>
<script src="{{asset('public/js/orden_show.js')}}"></script>

@endsection