app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'auth'],function(){

	Route::group(['middleware'=>'activo'],function(){

		Route::get('/inicio', ['as' =>'home.index' , 'uses' => 'HomeController@index']);

		Route::get('/', function () {
			return redirect()->route('home.index');
		});

		Route::get('perfil/index',['uses' => 'PerfilesController@index','as' => 'perfil.index']);
		Route::put('perfil/update/{user}',['uses' => 'PerfilesController@update','as' => 'perfil.update']);
		
		Route::get('solicitudes/{solicitud}/aprobar', ['as' =>'solicitudes.aprobar' , 'uses' => 'SolicitudesLivianosController@aprobar']);
		Route::put('solicitudes/{solicitud}/rechazar', ['as' =>'solicitudes.rechazar' , 'uses' => 'SolicitudesLivianosController@rechazar']);
		Route::get('solicitudes/{estado}/getCiudad', ['as' =>'solicitudes.getCiudad' , 'uses' => 'SolicitudesLivianosController@getCiudad']);
		Route::get('solicitudes/listar/{option?}', ['as' =>'solicitudes.listar' , 'uses' => 'SolicitudesLivianosController@listar']);
		Route::get('solicitudes/supervisor', ['as' =>'solicitudes.supervisor' , 'uses' => 'SolicitudesLivianosController@supervisor']);
		Route::resource('solicitudes', 'SolicitudesLivianosController');

		Route::get('sitios/padres', 'SitiosController@padres');
		Route::get('sitios/listar', ['as' =>'sitios.listar' , 'uses' => 'SitiosController@listar']);
		Route::resource('sitios', 'SitiosController');

		Route::group(['middleware'=>'user_admin'],function(){
			Route::get('usuarios/listar', ['as' =>'usuarios.listar' , 'uses' => 'UsuariosController@listar']);
			Route::get('usuarios', ['as' =>'usuarios.index' , 'uses' => 'UsuariosController@index']);
			Route::post('usuarios', ['as' =>'usuarios.store' , 'uses' => 'UsuariosController@store']);
			Route::delete('usuarios/{usuario}', ['as' =>'usuarios.destroy' , 'uses' => 'UsuariosController@destroy']);
			Route::put('usuarios/{usuario}', ['as' =>'usuarios.update' , 'uses' => 'UsuariosController@update']);	
			Route::get('usuarios/{usuario}', ['as' =>'usuarios.show' , 'uses' => 'UsuariosController@show']);
			Route::get('departamentos/opciones', 'DepartamentosController@opciones');
			Route::get('departamentos/listar', ['as' =>'departamentos.listar' , 'uses' => 'DepartamentosController@listar']);
			Route::resource('departamentos', 'DepartamentosController');
			Route::get('roles/listar', ['as' =>'roles.listar' , 'uses' => 'RolesController@listar']);
			Route::resource('roles', 'RolesController');
			Route::get('/mantenimiento', function () {
				$li='mantenimiento';
				return view('dashboard.mantenimiento.index')->with('li',$li);
				});		
		});

		Route::group(['middleware'=>'app_admin'],function(){
			Route::get('empleados/listar', ['as' =>'empleados.listar' , 'uses' => 'EmpleadosController@listar']);
			Route::resource('empleados', 'EmpleadosController');

			Route::get('proveedores/listar', ['as' =>'proveedores.listar' , 'uses' => 'ProveedoresController@listar']);
			Route::resource('proveedores', 'ProveedoresController');

			Route::get('proveedores/listar', ['as' =>'proveedores.listar' , 'uses' => 'ProveedoresController@listar']);
			Route::resource('proveedores', 'ProveedoresController');

			Route::get('viajes/{viaje}/por_unidad', ['as' =>'viajes.por_unidad' , 'uses' => 'ViajesController@por_unidad']);
			Route::get('viajes/cerrados', ['as' =>'viajes.cerrados' , 'uses' => 'ViajesController@cerrados']);
			Route::put('viajes/completar/{viaje}', ['as' =>'viajes.completar' , 'uses' => 'ViajesController@completar']);
			Route::get('viajes/{viaje}/cerrar', ['as' =>'viajes.cerrar' , 'uses' => 'ViajesController@cerrar']);
			Route::put('viajes/asignar', ['as' =>'viajes.asignar' , 'uses' => 'ViajesController@asignar']);
			Route::get('viajes/opciones', 'ViajesController@opciones');
			Route::post('viajes/nuevo', ['as' =>'viajes.nuevo' , 'uses' => 'ViajesController@nuevo']);
			Route::put('viajes/solicitudes_rechazar', ['as' =>'viajes.solicitudes_rechazar' , 'uses' => 'ViajesController@solicitudes_rechazar']);
			Route::get('viajes/solicitudes_listar/{option?}', ['as' =>'viajes.solicitudes_listar' , 'uses' => 'ViajesController@solicitudes_listar']);
			Route::get('viajes/listar/{option?}', ['as' =>'viajes.listar' , 'uses' => 'ViajesController@listar']);
			Route::resource('viajes', 'ViajesController');		

			Route::get('movimientos/listar', ['as' =>'movimientos.listar' , 'uses' => 'MovimientosController@listar']);
			Route::get('movimientos/{articulo}/movimientos', ['as' =>'movimientos.movimientos' , 'uses' => 'MovimientosController@movimientos']);
			Route::resource('movimientos', 'MovimientosController');

			Route::get('articulos/listar', ['as' =>'articulos.listar' , 'uses' => 'ArticulosController@listar']);
			Route::resource('articulos', 'ArticulosController');

			Route::get('activos/{activo}/pdf', ['as' =>'activos.pdf' , 'uses' => 'ActivosController@pdf']);
			Route::get('activos/listar', ['as' =>'activos.listar' , 'uses' => 'ActivosController@listar']);
			Route::resource('activos', 'ActivosController');

			Route::get('reportes/listar', ['as' =>'reportes.listar' , 'uses' => 'ReporteController@listar']);
			Route::resource('reportes', 'ReporteController');

			Route::get('ordenes/{orden}/pdf', ['as' =>'ordenes.pdf' , 'uses' => 'OrdenController@pdf']);
			Route::put('ordenes/completar/{orden}', ['as' =>'ordenes.completar' , 'uses' => 'OrdenController@completar']);
			Route::get('ordenes/{orden}/cambiar/{estado}', ['as' =>'ordenes.cambiar' , 'uses' => 'OrdenController@cambiar']);
			Route::delete('ordenes/borrar_movimiento/{movimiento}', ['as' =>'ordenes.borrar_movimiento' , 'uses' => 'OrdenController@borrar_movimiento']);
			Route::get('ordenes/getArticulos', ['as' =>'ordenes.getArticulos' , 'uses' => 'OrdenController@getArticulos']);
			Route::post('ordenes/agregar_tarea', ['as' =>'ordenes.agregar_tarea' , 'uses' => 'OrdenController@agregar_tarea']);
			Route::delete('ordenes/{orden}/borrar_tarea/{tarea}', ['as' =>'ordenes.borrar_tarea' , 'uses' => 'OrdenController@borrar_tarea']);
			Route::get('ordenes/{activo}/getTareas', ['as' =>'ordenes.getTareas' , 'uses' => 'OrdenController@getTareas']);
			Route::get('ordenes/listar', ['as' =>'ordenes.listar' , 'uses' => 'OrdenController@listar']);
			Route::resource('ordenes', 'OrdenController');

			//RUTAS DE LAS TAREAS CON ACTIVO ENLAZADO DE UNA VEZ
			Route::post('activo-tarea', ['as' =>'activo-tarea.store' , 'uses' => 'ActivoTareaController@store']);
			Route::get('activo-tarea/{pivot}', ['as' =>'activo-tarea.show' , 'uses' => 'ActivoTareaController@show']);
			Route::put('activo-tarea/{pivot}', ['as' =>'activo-tarea.update' , 'uses' => 'ActivoTareaController@update']);
			Route::delete('activo-tarea/{activo}/{tarea}', ['as' =>'activo-tarea.destroy' , 'uses' => 'ActivoTareaController@destroy']);
			Route::get('activo-tarea/{activo}/listar', ['as' =>'activo-tarea.listar' , 'uses' => 'ActivoTareaController@listar']);

			//RUTAS DE LOS REPORTES CON ACTIVO ENLAZADO DE UNA VEZ
			Route::get('activo-reporte/{reporte}/orden', ['as' =>'activo-reporte.orden' , 'uses' => 'ActivoReporteController@orden']);
			Route::get('activo-reporte/{reporte}/pdf', ['as' =>'activo-reporte.pdf' , 'uses' => 'ActivoReporteController@pdf']);
			Route::get('activo-reporte/{reporte}', ['as' =>'activo-reporte.show' , 'uses' => 'ActivoReporteController@show']);
			Route::get('activo-reporte/{activo}/listar', ['as' =>'activo-reporte.listar' , 'uses' => 'ActivoReporteController@listar']);

			//RUTAS DE LOS ARCHIVOS CON ACTIVO ENLAZADO DE UNA VEZ
			Route::get('activo-archivo/{activo}/nuevo', ['as' =>'activo-archivo.crear' , 'uses' => 'ActivoArchivoController@crear']);
			Route::get('activo-archivo/{activo}/listar', ['as' =>'activo-archivo.listar' , 'uses' => 'ActivoArchivoController@listar']);
			Route::resource('activo-archivo', 'ActivoArchivoController');

			//RUTAS DE LAS ORDENES CON ACTIVO Y/O ENLAZADO DE UNA VEZ
			Route::get('activo-orden/{activo}/nuevo', ['as' =>'activo-orden.nuevo' , 'uses' => 'ActivoOrdenController@nuevo']);
			Route::get('activo-orden/{activo}/listar', ['as' =>'activo-orden.listar' , 'uses' => 'ActivoOrdenController@listar']);			
		});
	});
});


Route::auth();

app/Activo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Activo extends Model
{
    protected $table = 'activos';
    protected $fillable = [
                            'unidad',
							'placa',
                            'marca',
                            'modelo',
							'serial',
                            'estatus',
                            'nro_activo',
                            'puestos',
                            'prioridad',
                            'clasificacion',
                            'tipo',
                            'año',
							'color',
							'tipo_aceite',
							'filtro_aceite',
							'filtro_aire',
							'filtro_combustible',
							'filtro_agua',
                            'foto',
                            'mantenimiento',
                            'ubicacion_fija',
                            'ubicacion_temporal',
    							];
    public function medida()
    {
    	return $this->hasOne('App\Medida', 'activo_id');
    }
    public function tareas()
    {
    	return $this->belongsToMany('App\Tarea', 'activo_tarea')
                     ->withPivot('id','estado',
                    'horas','pre_horas','realizacion_horas',
                    'kilometros','pre_kilometros','realizacion_kilometros','prioridad','orden_id');
    }
    public function movimientos()
    {
        return $this->hasMany('App\Movimiento','activo_id');
    }
    public function reportes()
    {
        return $this->hasMany('App\Reporte', 'activo_id');
    }
    public function archivos()
    {
    	return $this->hasMany('App\Archivo', 'activo_id');
    }

    public function ordenes()
    {
        return $this->hasMany('App\Orden', 'activo_id');
    }
    public function viajes()
    {
        return $this->belongsToMany('App\Viaje', 'activo_viaje')
                     ->withPivot('id');
    }
}

resources/views/dashboard/activos/index.blade.php
@extends('templates.master')

@section('title', 'Unidades')

@section('css')

<!-- DataTables -->  
<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/datatables/dataTables.bootstrap.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/datatables/prueba/buttons.dataTables.min.css')}}">
<!-- Select2 -->  
<link rel="stylesheet" href="{{asset('public/plugins/select2/dist/css/select2.min.css') }}">

@endsection

@section('contenido')
<div class="row" >

  <div class="col-md-12">
    <div class="box box-success">
      <div class="box-body">
          <a class="btn btn-default"  data-toggle="modal" href='{{ route('activos.create') }}'><span class="text-success"><i class="fa fa-plus"></i></span> Agregar Unidad</a>
          <a href='javascript:void(0)' class="btn btn-default pull-right"  id="actualizar-activo"><i class="fa fa-repeat"></i> Actualizar</a><hr>
        <table class="table table-bordered table-hover table-striped" id="activos" width="100%" >
          <thead style="">
            <tr>
              <th style="text-align: center;"><span class="glyphicon glyphicon-info-sign" style="font-size: 20px"></span> </th>
              <th>Descripción</th>
              <th>Clasificación</th>
              <th>Estatus</th>
              <th>Ubicación</th>      
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th style="text-align: center;"><span class="glyphicon glyphicon-info-sign" style="font-size: 20px"></span> </th>
              <th>Descripción</th>
              <th>Clasificación</th>
              <th>Estatus</th>
              <th>Ubicación</th>      
            </tr>
          </tfoot>
        </table>
        <div  style="border-style:solid; border-width:1px;border-color: #E5E8E8;  text-align: center; font-family: Lucida Sans Unicode; color: #7B7D7D;">
          <div style="margin: 10px; display: inline-block; " >
            <span class="label label-danger"><i class="fa fa-fw fa-wrench"></i></span><br>
            Matenimiento pendiente            
          </div>
          <div style="margin: 10px; display: inline-block; " >
            <span class="label label-warning"><i class="fa fa-fw fa-tachometer"></i></span><br>
           Matenimiento acercándose            
          </div>           
        </div>
      </div><!-- /.box-body -->
  </div>
  
@endsection

@section('js')

<!-- DataTables -->
<script src="{{asset('public/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/prueba/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/prueba/jszip.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/prueba/buttons.html5.min.js')}}"></script>

<script src="{{asset('public/js/activo.js')}}"></script>

<script type="text/javascript">
  $.fn.dataTable.ext.errMode = 'throw';
</script>

@endsection 

resources/views/dashboard/activos/print-hoja-de-vida.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hoja de Vida de la Unidad Nro. {{$activo->nro_activo}}</title>
    <link rel="stylesheet" href="{{asset('public/dist/print.css') }}">
    <style type="text/css">

      div.CABEZA {
        font-family: Arial, Helvetica, sans-serif;
        border: 0px solid #F2F2F2;
        width: 100%;
        text-align: left;
        border-collapse: collapse;
      }
      .divTable.CABEZA .divTableCell {
        border: 1px solid #AAAAAA;
        font-size: 10px;
        padding: 6px 6px;
        background: #344563;
        color: white;
      }
     
      div.minimalistBlack {
        font-family: Arial, Helvetica, sans-serif;
        border: 0px solid #F2F2F2;
        text-align: left;
        border-collapse: collapse;
        width: 100%;
      }
      .divTable.minimalistBlack .divTableCell, .divTable.minimalistBlack .divTableHead {
        padding: 10px 10px;
        border: 1px solid #AAAAAAA;
      }
      .divTable.minimalistBlack .divTableBody .divTableCell {
        font-size: 10px;
      }
      /* DivTable.com */
      .divTable{ display: table; }
      .divTableRow { display: table-row; }
      .divTableHeading { display: table-header-group;}
      .divTableCell, .divTableHead { display: table-cell;}
      .divTableHeading { display: table-header-group;}
      .divTableFoot { display: table-footer-group;}
      .divTableBody { display: table-row-group;}
    </style>
  </head>
 <body class="clearfix">
    <script type="text/php">
    if ( isset($pdf) ) {
        $font = $fontMetrics->getFont("arial", "bold");
        $pdf->page_text(550, 18, "{PAGE_NUM} de {PAGE_COUNT}", $font, 8, array(0,0,0));
    }
    </script> 
    <div style="margin-top: 10px;margin-bottom: 20px;white-space: nowrap;">
      <img src="{{asset('public/image/logo_AmazonasTech_RIF.png') }}" class="pull-left" width="199">
        <div class="text-right">
          <b>Departamento de Gestión de Flota</b><br />
          <b>Hoja de Vida<b />
        </div>
    </div>
    <div class="divTable CABEZA">
      <div class="divTableBody">
        <div class="divTableRow">
          <div style="text-align: center;" class="divTableCell"><b>DETALLES DE LA UNIDAD</b></div>
        </div>
      </div>
    </div>    
    <div class="divTable minimalistBlack">
      <div class="divTableBody" >
        <div class="divTableRow">
          <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Unidad</b></div>
          <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Marca</b></div>
          <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Modelo</b></div>
          <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Placa</b></div>
          <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Nro. de Activo</b></div>
        </div>
        <div class="divTableRow">
          <div class="divTableCell">{{$activo->unidad}}</div>
          <div class="divTableCell">{{$activo->marca}}</div>
          <div class="divTableCell">{{$activo->modelo}}</div>
          <div class="divTableCell">{{$activo->placa}}</div>
          <div class="divTableCell">{{$activo->nro_activo}}</div>
        </div>
        <div class="divTableRow">
          <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Serial</b></div>
          <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Año</b></div>
          <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Estatus</b></div>
          <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Prioridad</b></div>
          <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Ubicación</b></div>
        </div>
        <div class="divTableRow">
          <div class="divTableCell">{{$activo->serial}}</div>
          <div class="divTableCell">{{$activo->año}}</div>
          <div class="divTableCell">{{$activo->estatus}}</div>
          <div class="divTableCell">{{$activo->prioridad}}</div>
          <div class="divTableCell">{{$activo->ubicacion_fija}}</div>
        </div>
        <div class="divTableRow">
            <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Tipo de Aceite</b></div>
            <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Filtro de Aceite</b></div>
            <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Filtro de Aire</b></div>
            <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Filtro de Combustible</b></div>
            <div style=" background: #EDF2F7; text-align: center;" class="divTableCell"><b>Filtro Separador de Agua</b></div>
        </div>
        <div class="divTableRow">
            <div class="divTableCell">{{$activo->tipo_aceite}}</div>
            <div class="divTableCell">{{$activo->filtro_aceite}}</div>
            <div class="divTableCell">{{$activo->filtro_aire}}</div>
            <div class="divTableCell">{{$activo->filtro_combustible}}</div>
            <div class="divTableCell">{{$activo->filtro_agua}}</div>
        </div>
      </div>
    </div><br />
    @if (count($activo->reportes) > 0)    
      <div class="divTable CABEZA">
        <div class="divTableBody">
          <div class="divTableRow">
            <div style="text-align: center;" class="divTableCell"><b>REPORTES DE FALLAS DE LA UNIDAD</b></div>
          </div>
        </div>
      </div>    
      <div class="divTable minimalistBlack">
        <div class="divTableBody" >
          <div class="divTableRow">
            <div style="background:#EDF2F7; text-align: center; vertical-align: middle; " class="divTableCell"><b>N° de Reporte</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Descripción de Fallas</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Reportado por</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Lugar y Fecha</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>OT</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Prioridad</b></div>
          </div>
          @foreach ($activo->reportes as $reporte)                    
              <div class="divTableRow">
                <div style="width: 8%;  text-align: center;" class="divTableCell">{{$reporte->id}}</div>
                <div style=" " class="divTableCell">
                  <?php $i=1; ?>
                  @foreach ($reporte->fallas as $falla)
                   {{$i}}. ({{$falla->tipo}}) {{$falla->nombre}}<br />
                   <?php $i++; ?>
                  @endforeach
                  Observaciones: {{$reporte->observacion}}
                </div>
                <div class="divTableCell">{{$reporte->informador}}<br />{{$reporte->ci_informador}}<br />{{$reporte->cargo_informador}}</div>
                <div class="divTableCell">{{$reporte->lugar}}<br />{{$reporte->fecha}}</div>
                <div class="divTableCell">
                @if($reporte->estado =='Sin asignar') {{$reporte->estado}}
                @else Nro. {{$reporte->orden->id}}
                @endif
                </div>
                <div class="divTableCell">{{$reporte->prioridad}}</div>
              </div>
          @endforeach
        </div>
      </div><br />
    @endif
    @if (count($activo->ordenes) > 0)    
      <div class="divTable CABEZA">
        <div class="divTableBody">
          <div class="divTableRow">
            <div style="text-align: center;" class="divTableCell"><b>ORDENES DE TRABAJO DE LA UNIDAD</b></div>
          </div>
        </div>
      </div>    
      <div class="divTable minimalistBlack">
        <div class="divTableBody" >
          <div class="divTableRow">
            <div style="background:#EDF2F7; text-align: center; vertical-align: middle; " class="divTableCell"><b>N° de OT</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Responsable</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Actividades</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Insumos</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Inicio/Fin</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Reporte</b></div>
          </div>
          @foreach ($activo->ordenes as $orden)                  
              <div class="divTableRow">
                <div style="width: 8%;  text-align: center;" class="divTableCell">{{$orden->id}}</div>
                <div class="divTableCell">{{$orden->empleado->nombre}}</div>
                <div style=" " class="divTableCell">
                  <?php $i=1; ?>
                  @foreach ($orden->tareas as $tarea)
                   {{$i}}. {{$tarea->nombre}}<br />
                  <?php $i++; ?>
                  @endforeach
                </div>
                <div style=" " class="divTableCell">
                  <?php $i=1; ?>
                  @foreach ($orden->movimientos as $movimiento)
                   {{$i}}. ({{$movimiento->cantidad}}) {{$movimiento->articulo->nombre}}-{{$movimiento->razon}}<br />
                  <?php $i++; ?>
                  @endforeach
                </div>
                <div class="divTableCell">{{$orden->inicia}} / {{$orden->termina}}</div>
                <div class="divTableCell"> @if(isset($orden->reporte_id))Nro. {{$orden->reporte_id}} @endif  </div>
              </div>
          @endforeach
        </div>
      </div><br />
    @endif
    @if (count($activo->viajes) > 0)    
      <div class="divTable CABEZA">
        <div class="divTableBody">
          <div class="divTableRow">
            <div style="text-align: center;" class="divTableCell"><b>VIAJES DE LA UNIDAD</b></div>
          </div>
        </div>
      </div>    
      <div class="divTable minimalistBlack">
        <div class="divTableBody" >
          <div class="divTableRow">
            <div style="background:#EDF2F7; text-align: center; vertical-align: middle; " class="divTableCell"><b>N° de Viaje</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Chofer Asignado</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Status</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Origen</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Destino</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Fecha de Salida</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Fecha de Legada</b></div>
            <div style="background:#EDF2F7; vertical-align: middle;" class="divTableCell"><b>Solicitudes Asociadas</b></div>
          </div>
          @foreach ($activo->viajes as $viaje)                  
              <div class="divTableRow">
                <div style="width: 8%;  text-align: center;" class="divTableCell">{{$viaje->id}}</div>
                <div class="divTableCell">{{$viaje->chofer->nombre}}</div>
                <div class="divTableCell">{{$viaje->estado}}</div>
                <div class="divTableCell">{{$viaje->origen}}</div>
                <div class="divTableCell">{{$viaje->destino}}</div>
                <div class="divTableCell">{{$viaje->fecha_salida}}</div>
                <div class="divTableCell">{{$viaje->fecha_llegada}}</div>
                <div style=" " class="divTableCell">
                  @foreach ($viaje->solicitudes as $solicitud)
                   {{$solicitud->id}}. {{$solicitud->solicitante->nombre}}<br />
                  @endforeach
                </div>
              </div>
          @endforeach
        </div>
      </div><br />
    @endif       
  </body>
</html>